<?php

/* Simple table of contents module crashes if ampersand is present in node->body
 * To prevent this an ampersand substitution is done in tbx_amp_helper_node_view.
 * to call the substitution before toc_node_view, the oder of hook implementations is altered
 */

function tbx_amp_helper_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'node_view') {
  	// see https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_module_implements_alter/7
    // Move simple_table_of_contents() to the end of the list. 
    // to make sure ampersand is replaced befor.
    $group = $implementations['simple_table_of_contents'];
    if(isset($group)) {
    	unset($implementations['simple_table_of_contents']);
    	$implementations['simple_table_of_contents'] = $group;
    }
  }
}

/** substitute ampersand for simple_table_of_contents
 * Implements hook_node_view().
 */

function tbx_amp_helper_node_view($node, $view_mode, $langcode) {
  // Only add a table of contents to nodes with a body
 
  if (isset($node->content['body'])) {
    // Get the node's body text
    $body = $node->content['body'][0]['#markup'];

    $body = preg_replace("/&/", '&amp;', $body);

    $node->content['body'][0]['#markup'] = $body;
   
  } 
}


